### PR TITLE
move responsibility for database write to main process

### PR DESCRIPTION
**Pull request by fippo**
this allows things like batching requests more easily

### CODE REVIEW

**Comment by fippo** [comment]
moving the "to storage" to the main process might have quite some advantages.
In particular we currently
* unzip the file to extract the data
* zip it again to put it into storage

By moving things to the main process we can avoid zipping it again.

**Comment by ggarber** [comment]
I thought the batching was going to be done inside each child, but this approach looks good to me too.

I like having the storage and the database writes in the same place.

I'm ok to store by default even if there is no peerconnection, although you could also check the features extracted to decide if it deserves being stored.

**Comment by fippo** [comment]
the children/workers created for each job so can't have state. Will move the store put to the main process too.

**Comment by fippo** [comment]
done. Now i actually need to test that in production...

**Comment by ggarber** [comment]
"the children/workers created for each job so can't have state." right now yes, i was thinking on persistent workers reading jobs.

But as I said your approach in this PR LGTM too.   Good job!

**Comment by fippo** [comment]
seems to work well, merging. Tagging @dagingaa just in case

**Pull request merged**
